services:
  db:
    build: /docker/db
    ports:
      - 5432:5432
    env_file: /.db.env
    volumes:
      - /docker/db/init.sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 15s
      timeout: 15s
      retries: 5
    cpus: 0.25
  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - 3000:3000
    entrypoint: ["/entrypoint.sh"]
    environment:
      - WAIT_HOSTS=db:5432
    cpus: 0.25
      