services:
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    shm_size: 512mb
    env_file:
      - ./.db.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports: 
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    links: 
        - db