import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <nav className="top-nav-container">
               <div className="x-padded-centered-container">
                  <div className="top-nav-padded-container">
                     <div></div>
                     <div className="flex items-center h-full gap-8">
                        <div className="text-[32px]">Task</div>
                        <div className="text-[32px]">Profile</div>
                     </div>
                     <div className="text-[36px]">Hello ALOY</div>
                  </div>
               </div>
            </nav>
            {children}
         </body>
      </html>
   );
}
